environment:
  node_js_version: "4.1.1"
  TSD_GITHUB_TOKEN: "8742b29e67faa29aa25564ff7317b50fd7c1327d"
  clone_depth: 1

install:
  - ps: start-filedownload https://az764295.vo.msecnd.net/public/0.10.1-release/VSCode-win32.zip
  - ps: 7z.exe x .\VSCode-win32.zip -oC:\VSCode > $null
  - ps: install-product node $env:node_js_version
  - npm install
  - npm install -g gulp
  - gulp init
  - C:\VSCode\bin\code.cmd

build: off

test_script:
  - node --version
  - npm --version
  - gulp
